version: "3.7"

services:
  db:
    image: kartoza/postgis
    volumes:
      - dbdata:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASS: development
      POSTGRES_DBNAME: mozio
      POSTGRES_USER: mozio
    ports:
      - "54324:5432"
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: mozio
    restart: always
    volumes:
      - .:/mozio
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:postgisdb
volumes:
  dbdata:
