# Generated by Django 2.2.2 on 2019-06-29 04:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_areas_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_areas_api.Provider')),
            ],
            options={
                'verbose_name': 'service_area',
                'verbose_name_plural': 'service_areas',
                'db_table': 'service_area',
            },
        ),
    ]
